"""Shared layout and animation constants for the draw screen and its sub-modules."""

# ── Deck layout ──────────────────────────────────────────────────────
NUM_DECK_CARDS = 48
DECK_ROW_COUNT = 4
DECK_CARD_WIDTH = 9
DECK_CARD_HEIGHT = 7
SPREAD_SLOT_WIDTH = 16
SPREAD_SLOT_HEIGHT = 12

# ── Animation timing ─────────────────────────────────────────────────
DECK_HIDE_DELAY = 0.42
PICK_COMPLETE_DELAY = 0.0
SPREAD_RECENTER_OFFSET = 4
SPREAD_RECENTER_DURATION = 0.28
SLOT_PLACE_OFFSET = 2
SLOT_PLACE_DURATION = 0.22
SLOT_FLIP_FADE_OUT = 0.14
SLOT_FLIP_SWAP_PAUSE = 0.02
SLOT_FLIP_FADE_IN = 0.28
SLOT_FLIP_GLOW_HOLD = 0.16
DECK_ENTRANCE_STAGGER = 0.015
DECK_ENTRANCE_FADE = 0.28
SPREAD_SLOT_ENTRANCE_STAGGER = 0.07
SPREAD_SLOT_ENTRANCE_FADE = 0.28

# ── Interpretation dialog layout ─────────────────────────────────────
INTERP_PANEL_HEIGHT = "46%"  # CSS-only; runtime code uses _panel_height_cells()
INTERP_PANEL_HEIGHT_RATIO = 0.46
INTERP_MIN_HEIGHT = 14
INTERP_MAX_HEIGHT = 30
INTERP_SIDE_MARGIN = 1
INTERP_DETAIL_GAP = 0
INTERP_FULL_SIDE_MARGIN = 5
INTERP_FULL_WIDTH_CORRECTION = 4
INTERP_FULLSCREEN_VERTICAL_CHROME = 5
INTERP_FULLSCREEN_SIDE_MARGIN = 1
DETAIL_PANEL_WIDTH = 66
FOLLOWUP_BOTTOM_MARGIN = 5
